# Generated by Django 2.1.1 on 2018-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('pojemnosc', models.IntegerField(blank=True, null=True)),
                ('ilosc_cyl', models.IntegerField(blank=True, null=True)),
                ('rodzaj_silnika', models.CharField(choices=[('diezel', 'Diezel'), ('benzyna', 'Benzyna'), ('parowy', 'Parowy'), ('elektryczny', 'Elektryczny'), ('inny', 'Inny')], max_length=255)),
                ('opis', models.TextField()),
            ],
        ),
    ]
