# Generated by Django 2.1.1 on 2018-09-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255)),
                ('model', models.TextField(max_length=255)),
                ('typ_nadwozia', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('kombi', 'Kombi'), ('wan', 'Wan')], max_length=50, null=True)),
                ('rok_prod', models.IntegerField()),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='engines.Engine')),
            ],
        ),
    ]
